# Generated by Django 4.1 on 2022-10-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='user',
            new_name='usuario',
        ),
    ]
