# Generated by Django 4.1 on 2022-10-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_rename_user_pessoa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasci',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='texto',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
