# Generated by Django 4.1 on 2022-10-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_pessoa_imagem_alter_pessoa_data_nasci_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_nasci',
            new_name='DataNasci',
        ),
    ]
